The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) XALT/minimal   2) slurm   3) NeSI
Lmod has detected the following error: Cannot load module "NIWA" because these
module(s) are loaded:
   NeSI

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    NIWA             /opt/nesi/modulefiles/NIWA.lua

Lmod has detected the following error: The following module(s) are unknown:
"OCI/12.2"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "OCI/12.2"

Also make sure that all modulefiles written in TCL start with the string
#%Module



Lmod has detected the following error: The following module(s) are unknown:
"OCI/12.2"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "OCI/12.2"

Also make sure that all modulefiles written in TCL start with the string
#%Module



The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) XALT/minimal   2) slurm   3) NeSI
Lmod has detected the following error: The following module(s) are unknown:
"gcc/9.3.0"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "gcc/9.3.0"

Also make sure that all modulefiles written in TCL start with the string
#%Module



Thu May  2 22:53:42 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:85:00.0 Off |                    0 |
| N/A   26C    P0    59W / 400W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
2024-05-02 22:53:44.892411: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
<xarray.DataArray 'orog' ()>
array(1733.36035156) <xarray.DataArray 'he' ()>
array(1157.46264648) <xarray.DataArray 'vegt' ()>
array(17.00000763)
[                                        ] | 0% Completed |  0.0s[##################################      ] | 85% Completed |  0.1s
Traceback (most recent call last):
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/xarray/coding/times.py", line 236, in decode_cf_datetime
    dates = _decode_datetime_with_pandas(flat_num_dates, units, calendar)
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/xarray/coding/times.py", line 176, in _decode_datetime_with_pandas
    raise OutOfBoundsDatetime(
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Cannot decode times from a non-standard calendar, '365_day', using pandas.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ops/train_model_gust.py", line 50, in <module>
    y = y.load().transpose("time", "lat", "lon")
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/xarray/core/dataset.py", line 865, in load
    evaluated_data = da.compute(*lazy_data.values(), **kwargs)
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/dask/base.py", line 452, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/dask/threaded.py", line 76, in get
    results = get_async(
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/dask/array/core.py", line 100, in getter
    c = np.asarray(c)
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/xarray/core/indexing.py", line 354, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/xarray/core/indexing.py", line 518, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/xarray/core/indexing.py", line 419, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/xarray/coding/variables.py", line 70, in __array__
    return self.func(self.array)
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/xarray/coding/times.py", line 243, in decode_cf_datetime
    dates[np.nanargmin(num_dates)].year < 1678
  File "<__array_function__ internals>", line 5, in nanargmin
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/numpy/lib/nanfunctions.py", line 495, in nanargmin
    res = np.argmin(a, axis=axis)
  File "<__array_function__ internals>", line 5, in argmin
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 1269, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)
  File "/nesi/project/niwa00004/rampaln/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence
